version: '3.5'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs
    ports:
      - '3000:3000'
    depends_on:
      - backend
    # volumes:
    #   - ./src:/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nestjs
    ports:
      - '3005:3005'
    depends_on:
      - mongo
    # volumes:
    #   - ./src:/app/src
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example